=== dshah29/Tibco-Code/MSF_CCS/Shared Archive/SharedResources/SchemaDefinitions/Internal/Common/CommonDefinitions/MSF/Enumerations_v1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns:enum="http://three.co.uk/xsd/resource/common/commondefinitions/msf/enumerations/v1"
	 targetNamespace="http://three.co.uk/xsd/resource/common/commondefinitions/msf/enumerations/v1"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:complexType name="EnumerationSet">
		<xs:sequence>
<xs:choice maxOccurs="unbounded">
			<xs:element ref="enum:enumeration"/>
			<xs:element ref="enum:regexp"/>
</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="caseSensitive" type="xs:boolean" use="required"/>
		<xs:attribute name="normalised" type="xs:boolean" use="required"/>
		<xs:attribute name="useSpaces" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:element name="EnumerationSet" type="enum:EnumerationSet"/>
	<xs:complexType name="EnumerationSets">
		<xs:sequence>
			<xs:element ref="enum:EnumerationSet" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="EnumerationSets" type="enum:EnumerationSets"/>
	<xs:complexType name="enumeration">
		<xs:simpleContent>
			<xs:extension base="enum:EmptyString">
				<xs:attribute name="value" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="regexp">
		<xs:simpleContent>
			<xs:extension base="enum:EmptyString">
				<xs:attribute name="expression" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="enumeration" type="enum:enumeration"/>
	<xs:element name="regexp" type="enum:regexp"/>
	<xs:simpleType name="EmptyString">
		<xs:restriction base="xs:string">
			<xs:maxLength value="0"/>
			<xs:minLength value="0"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dshah29/Tibco-Code/MSF_CustomerDatabase/Shared Archive/SharedResources/XML/Common/CommonDefinitions/MSF/StandardEnumerations.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<EnumerationSets xmlns = "http://three.co.uk/xsd/resource/common/commondefinitions/msf/enumerations/v1" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "http://three.co.uk/xsd/resource/common/commondefinitions/msf/enumerations/v1 ../../../../SchemaDefinitions/Internal/Common/CommonDefinitions/MSF/Enumerations_v1.xsd">
	<EnumerationSet caseSensitive = "false" name = "Enterprise/EnterpriseSecurity/EnterpriseSecurityEvents/MCAudit/v1:AUDIT_EVENT_TYPE" normalised = "true" useSpaces = "true">
		<enumeration value = "CUSTOMER_VALIDATION"/>
		<enumeration value = "CUSTOMER_SEARCH"/>
		<enumeration value = "INTERACTION_NOTE"/>
		<enumeration value = "AGENT_LOGIN"/>
		<enumeration value = "AGENT_LOGOUT"/>
		<enumeration value = "ACCESS_MY3"/>
		<enumeration value = "LOGOUT_MY3"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Asset/AssetCommon/AssetEnumerations/AssetStatus/v1:STOCK_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "OUTOFSTOCK"/>
		<enumeration value = "INSTOCK"/>
		<enumeration value = "LOWSTOCK"/>
		<enumeration value = "PREORDER"/>
		<enumeration value = "ENDOFLIFE"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Asset/AssetCommon/AssetEnumerations/AssetStatus/v1:LOCATION_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "ACTIVE"/>
		<enumeration value = "INACTIVE"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Asset/AssetCommon/AssetEnumerations/AssetStatus/v1:RESERVATION_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "EXPIRED"/>
		<enumeration value = "RESERVED"/>
		<enumeration value = "COMMITTED"/>
		<enumeration value = "CANCELLED"/>
		<enumeration value = "FAILED"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Asset/AssetCommon/AssetEnumerations/AssetTypes/v1:LOCATION_TYPES" normalised = "true" useSpaces = "true">
		<enumeration value = "STORE"/>
		<enumeration value = "WAREHOUSE"/>
		<enumeration value = "CALLCENTRE"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Billing/BillingCommon/BillingEnumerations/BillingStatus/v1:BILLING_ACCOUNT_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "OPEN"/>
		<enumeration value = "SUSPENDED"/>
		<enumeration value = "CANCELLED"/>
		<enumeration value = "CLOSED"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Billing/BillingCommon/BillingEnumerations/BillingStatus/v1:DIRECT_DEBIT_MANDATE_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "ISSUED"/>
		<enumeration value = "CANCELLED"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Billing/BillingCommon/BillingEnumerations/BillingTypes/v1:PAYMENT_TYPES" normalised = "true" useSpaces = "true">
		<enumeration value = "CREDITCARD"/>
		<enumeration value = "DEBITCARD"/>
		<enumeration value = "DIRECTDEBIT"/>
		<enumeration value = "CARD"/>
		<enumeration value = "CASH"/>
		<enumeration value = "CHEQUE"/>
		<enumeration value = "VOUCHER"/>
		<enumeration value = "ADDTOBILL"/>
		<enumeration value = "PAYATTILL"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Billing/BillingCommon/BillingEnumerations/BillingTypes/v1:PAYMENT_CARD_TYPE" normalised = "true" useSpaces = "true">
		<enumeration value = "Visa Electron"/>
		<enumeration value = "Amex"/>
		<enumeration value = "Visa Delta"/>
		<enumeration value = "Mastercard"/>
		<enumeration value = "Laser"/>
		<enumeration value = "Visa"/>
		<enumeration value = "JCB"/>
		<enumeration value = "Solo"/>
		<enumeration value = "Switch"/>
		<enumeration value = "Unknown"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/Address/v1:ADDRESS_TYPES" normalised = "true" useSpaces = "true">
		<enumeration value = "BILLING"/>
		<enumeration value = "HOME"/>
		<enumeration value = "WORK"/>
		<enumeration value = "COLLECTION"/>
		<enumeration value = "DELIVERY"/>
		<enumeration value = "STORE"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/Address/v1:RESIDENT_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "OWNER"/>
		<enumeration value = "TENANT"/>
		<enumeration value = "PARENTS"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/Appointments/v1:APPOINTMENT_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "PENDING"/>
		<enumeration value = "ATTENDED"/>
		<enumeration value = "NOT ATTENDED"/>
		<enumeration value = "CANCELLED"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/Appointments/v1:APPOINTMENT_TYPES" normalised = "true" useSpaces = "true">
		<enumeration value = "COLLECTION"/>
		<enumeration value = "INQUIRY"/>
		<enumeration value = "PROBLEM"/>
		<enumeration value = "DEMONSTRATION"/>
		<enumeration value = "DROPOFF"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/CreditProfileReference/v1:CREDIT_REF_TYPE" normalised = "true" useSpaces = "true">
		<enumeration value = "CREDIT"/>
		<enumeration value = "SAVINGS"/>
		<enumeration value = "STOCK"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/Discount/v1:DISCOUNT_TYPE" normalised = "true" useSpaces = "true">
		<enumeration value = "PROMOTION"/>
		<enumeration value = "BUSINESS"/>
		<enumeration value = "MANAGEMENT DISCRETION"/>
		<enumeration value = "ADD OFF"/>
		<enumeration value = "DISPLAY / DAMAGED"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/Discount/v1:DISCOUNT_CALCULATION_TYPE" normalised = "true" useSpaces = "true">
		<enumeration value = "MONETARY"/>
		<enumeration value = "PERCENTAGE"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/Individual/v1:MARITAL_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "MARRIED"/>
		<enumeration value = "SEPARATED"/>
		<enumeration value = "SINGLE"/>
		<enumeration value = "DIVORCED"/>
		<enumeration value = "WIDOWED"/>
		<enumeration value = "NOT DISCLOSED"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/Individual/v1:EMPLOYMENT_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "EMPLOYED"/>
		<enumeration value = "SELF EMPLOYED"/>
		<enumeration value = "UNEMPLOYED"/>
		<enumeration value = "STUDENT"/>
		<enumeration value = "RETIRED"/>
		<enumeration value = "SOLE TRADER"/>
		<enumeration value = "COMPANY DIRECTOR"/>
		<enumeration value = "PARTNERSHIP"/>
		<enumeration value = "OTHER"/>
		<enumeration value = "PART TIME"/>
		<enumeration value = "CORPORATE EMPLOYEE"/>
		<enumeration value = "NON UK STUDENT"/>
		<enumeration value = "DEPENDANT SPOUSE"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/Interaction/v1:INTERACTION_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "PENDING"/>
		<enumeration value = "CLOSED"/>
		<enumeration value = "OPEN"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonDefinitions/Party/v1:PARTY_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "ACTIVE"/>
		<enumeration value = "INACTIVE"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonEnumerations/DateFrequency/v1:DATEFREQUENCY" normalised = "true" useSpaces = "true">
		<enumeration value = "SINGLE"/>
		<enumeration value = "WEEKLY"/>
		<enumeration value = "MONTHLY"/>
		<enumeration value = "QUARTERLY"/>
		<enumeration value = "YEARLY"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonEnumerations/Status/v1:ACCOUNT_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "OPEN"/>
		<enumeration value = "CLOSED"/>
		<enumeration value = "SUSPENDED"/>
		<enumeration value = "CANCELLED"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonEnumerations/Status/v1:PRICE_SEGMENT" normalised = "true" useSpaces = "true">
		<enumeration value = "ONLINE"/>
		<enumeration value = "RETAIL"/>
		<enumeration value = "CONTACTCENTRE"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Common/CommonEnumerations/Status/v1:ACCOUNTTYPE_SEGMENT" normalised = "true" useSpaces = "true">
		<enumeration value = "SIMO"/>
		<enumeration value = "CHS"/>
		<enumeration value = "MBB"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Customer/CustomerAccount/CustomerAccountManagement/CustomerAccount/v1:ACCOUNT_TYPE" normalised = "true" useSpaces = "true">
		<enumeration value = "CONTRACT"/>
		<enumeration value = "PAYG"/>
		<enumeration value = "HYBRID"/>
		<enumeration value = "SHARER"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Customer/CustomerAccount/CustomerAccountManagement/CustomerAccount/v1:ACCOUNT_LEVEL" normalised = "true" useSpaces = "true">
		<enumeration value = "Parent"/>
		<enumeration value = "Child"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Customer/CustomerAccount/CustomerAccountManagement/CustomerAccount/v1:ACCOUNT_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "Active"/>
		<enumeration value = "Suspended"/>
		<enumeration value = "Closed"/>
		<enumeration value = "Pending Activation"/>
		<enumeration value = "Activation"/>
		<enumeration value = "Pending Suspension"/>
	</EnumerationSet>
	<EnumerationSet caseSensitive = "false" name = "Customer/CustomerAccount/CustomerAccountManagement/CustomerAccount/v1:SERVICE_STATUS" normalised = "true" useSpaces = "true">
		<enumeration value = "INS"/>
		<enumeration value = "DIS"/>
		<enumeration value = "SUS-COLL"/>
		<enumeration value = "SUS-CUST"/>
